src/main/java/com/ux/pojo/FreteWS.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ux.pojo;

import com.thoughtworks.xstream.XStream;
import com.thoughtworks.xstream.annotations.XStreamAlias;
import com.thoughtworks.xstream.io.xml.DomDriver;
import com.ux.util.UXUtil;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.regex.Pattern;

/**
 *
 * @author Renato
 */
@XStreamAlias("Servico")
public class FreteWS {

    private String cServico;
    private String Codigo;
    private String Valor;
    private String PrazoEntrega;
    private String ValorSemAdicionais;
    private String ValorMaoPropria;
    private String ValorAvisoRecebimento;
    private String ValorValorDeclarado;
    private String EntregaDomiciliar;
    private String EntregaSabado;
    private String MsgErro;
    private String Erro;

    public String getcServico() {
        return cServico;
    }

    public void setcServico(String cServico) {
        this.cServico = cServico;
    }

    public String getCodigo() {
        return Codigo;
    }

    public void setCodigo(String Codigo) {
        this.Codigo = Codigo;
    }

    public String getValor() {
        return Valor;
    }

    public void setValor(String Valor) {
        this.Valor = Valor;
    }

    public String getPrazoEntrega() {
        return PrazoEntrega;
    }

    public void setPrazoEntrega(String PrazoEntrega) {
        this.PrazoEntrega = PrazoEntrega;
    }

    public String getValorSemAdicionais() {
        return ValorSemAdicionais;
    }

    public void setValorSemAdicionais(String ValorSemAdicionais) {
        this.ValorSemAdicionais = ValorSemAdicionais;
    }

    public String getValorMaoPropria() {
        return ValorMaoPropria;
    }

    public void setValorMaoPropria(String ValorMaoPropria) {
        this.ValorMaoPropria = ValorMaoPropria;
    }

    public String getValorAvisoRecebimento() {
        return ValorAvisoRecebimento;
    }

    public void setValorAvisoRecebimento(String ValorAvisoRecebimento) {
        this.ValorAvisoRecebimento = ValorAvisoRecebimento;
    }

    public String getValorValorDeclarado() {
        return ValorValorDeclarado;
    }

    public void setValorValorDeclarado(String ValorValorDeclarado) {
        this.ValorValorDeclarado = ValorValorDeclarado;
    }

    public String getEntregaDomiciliar() {
        return EntregaDomiciliar;
    }

    public void setEntregaDomiciliar(String EntregaDomiciliar) {
        this.EntregaDomiciliar = EntregaDomiciliar;
    }

    public String getEntregaSabado() {
        return EntregaSabado;
    }

    public void setEntregaSabado(String EntregaSabado) {
        this.EntregaSabado = EntregaSabado;
    }

    public String getMsgErro() {
        return MsgErro;
    }

    public void setMsgErro(String MsgErro) {
        this.MsgErro = MsgErro;
    }

    public String getErro() {
        return Erro;
    }

    public void setErro(String Erro) {
        this.Erro = Erro;
    }

    public FreteWS consultarFrete(Map<String, Object> params) throws MalformedURLException, IOException {
        URL url;
        String urll = "http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?" + UXUtil.curl(params);
        System.out.println(urll);
        url = new URL(urll);
        StringBuilder xml = new StringBuilder();
        BufferedReader reader = new BufferedReader(new InputStreamReader(url.openStream(), "UTF-8"));
        for (String line; (line = reader.readLine()) != null;) {
            xml.append(line);
        }

        String xmlSaida = "";
        xmlSaida = xml.toString().replace("<Servicos>", "").replace("</Servicos>", "");
        XStream read = new XStream(new DomDriver());
        read.alias("cServico", FreteWS.class);
        FreteWS e = (FreteWS) read.fromXML(xmlSaida);
        return e;
    }

    public ServicosFreteWS consultarFreteAutomaticoPACSEDEX(Map<String, Object> params) throws MalformedURLException, UnsupportedEncodingException, IOException {
        URL url;
        String urll = "http://ws.correios.com.br/calculador/CalcPrecoPrazo.aspx?" + UXUtil.curl(params);
//        System.out.println(urll);
        url = new URL(urll);
        StringBuilder xml = new StringBuilder();
        BufferedReader reader = new BufferedReader(new InputStreamReader(url.openStream(), "UTF-8"));
        for (String line; (line = reader.readLine()) != null;) {
            xml.append(line);
        }

        XStream xStream = new XStream();
        xStream.processAnnotations(ServicosFreteWS.class);
        ServicosFreteWS servicosFreteWS = (ServicosFreteWS) xStream.fromXML(xml.toString());
        return servicosFreteWS;
    }
}

src/main/java/com/ux/pojo/Vendas.java
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ux.pojo;

import com.ux.model.Empresa;
import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * @author Renato
 */
public class Vendas {
    private String lote;
    private Date dtCompra;
    private BigDecimal valorTotal;
    private BigDecimal valorFrete;
    private String formaPagamento;
    private Empresa empresa;
    private String status;
    private String situacao;
    private int mes;

    public String getLote() {
        return lote;
    }

    public void setLote(String lote) {
        this.lote = lote;
    }

    public Date getDtCompra() {
        return dtCompra;
    }

    public void setDtCompra(Date dtCompra) {
        this.dtCompra = dtCompra;
    }

    public BigDecimal getValorTotal() {
        return valorTotal;
    }

    public void setValorTotal(BigDecimal valorTotal) {
        this.valorTotal = valorTotal;
    }

    public BigDecimal getValorFrete() {
        return valorFrete;
    }

    public void setValorFrete(BigDecimal valorFrete) {
        this.valorFrete = valorFrete;
    }

    public String getFormaPagamento() {
        return formaPagamento;
    }

    public void setFormaPagamento(String formaPagamento) {
        this.formaPagamento = formaPagamento;
    }

    public Empresa getEmpresa() {
        return empresa;
    }

    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSituacao() {
        return situacao;
    }

    public void setSituacao(String situacao) {
        this.situacao = situacao;
    }

    public int getMes() {
        return mes;
    }

    public void setMes(int mes) {
        this.mes = mes;
    }
    
}

src/main/webapp/Restrito/Vendas/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ux="http://java.sun.com/jsf/composite/ux"
      xmlns:f="http://java.sun.com/jsf/core">

    <body>

        <ui:composition template="./../../WEB-INF/Template-ADMIN.xhtml">
            <ui:define name="conteudo">
                <f:metadata>  
                    <f:event type="preRenderComponent" listener="#{vendasMB.carregarEmpresaSessao(controleSessaoMB.usuarioLogado.idEmpresa)}" />  
                </f:metadata> 
                <p:panel header="Vendas">
                    <h3>Pedidos</h3>
                    <p:messages closable="true" id="mess" />
                    <hr/>
                    <p:dataTable  value="#{vendasMB.vendasLazy}" 
                                  paginator="true" rows="10" lazy="true" var="vend" 
                                  id="vendas" emptyMessage="Nenhuma venda encontrada!" paginatorPosition="bottom" paginatorAlwaysVisible="false" >
                        <p:column  style="width: 16px">
                            <p:rowToggler />
                        </p:column>
                        <p:column headerText="Pedido" width="5%" style="font-size: 10px; text-align: center;">
                            <h:outputText value="#{controleSessaoMB.subString(vend.lote,4)}" />
                        </p:column>
                        <p:column headerText="Cliente" width="20%" style="font-size: 10px;">
                            <h:outputText value="#{vend.usuario.idCliente.primeiroNome} #{vend.usuario.idCliente.sobrenome} " />
                        </p:column>
                        <p:column headerText="Valor" width="10%" style="font-size: 10px;">
                            <ux:outputMoney value="#{vend.valor}" />
                        </p:column>

                        <p:column headerText="Data"  width="10%" style="font-size: 10px;">
                            <ux:outputDate value="#{vend.dt_venda}" />
                        </p:column>
                        <p:column headerText="Status"  width="8%" style="font-size: 10px;">
                            <h:outputText value="#{vend.status == 'IN_ANALISYS' ? 'Em Análise': vend.status}"   />
                        </p:column>
                        <p:column headerText="Entrega"  width="8%" style="font-size: 10px;">
                            <h:outputText value="#{vend.situacaoEntrega}"  />
                        </p:column>
                        <p:column   width="10%">
                            <p:commandButton icon="Frete" action="#{vendasMB.selecionarPedidos(vend.lote)}" disabled="#{vendasMB.checkEntrega(vend.situacaoEntrega)}" update=":frmRatreio" 
                                             oncomplete="PF('dlgConfirmarEnvio').show();" title="Confirmar Envio"  styleClass="btn btn-success" />
                            <p:commandButton icon="Excluir" title="Cancelar Pedido" disabled="#{vend.status != 'Aguardando pagamento'}" 
                                             styleClass="btn btn-danger" />
                        </p:column>
                        <p:rowExpansion>
                            <p:rowExpansion>
                                <h3>Produtos</h3>
                                <p:dataTable value="#{deliveryMB.listarComprasPorLote(vend.lote)}" var="prod">
                                    <p:column headerText="Produto" width="35%">
                                        <table>
                                            <tr >
                                                <td style="border: none !important; width: 120px;"><p:graphicImage value="/upload/Produto/#{prod.idProduto.idProduto}/#{prod.idProduto.fotoPrincipal}"  styleClass="img-responsive" style="width: 100px; height: 100px;" /></td>
                                                <td style="border: none !important;"><h:outputText value="#{prod.idProduto.nome}" /></td>
                                            </tr>
                                        </table>
                                    </p:column>
                                    <p:column headerText="Quantidade"  width="10%" styleClass="text-center">
                                        <h:outputText value="#{prod.quantidade}" />
                                    </p:column>
                                    <p:column  headerText="Valor" width="10%" styleClass="text-center">
                                        <h:outputText value="#{prod.valorCompra}" >
                                            <f:convertNumber type="currency" />
                                        </h:outputText>
                                    </p:column>
                                    <p:column headerText="Total" width="10%"  styleClass="text-center">
                                        <h:outputText value="#{prod.valorCompra.multiply(prod.quantidade)}" >
                                            <f:convertNumber type="currency" />
                                        </h:outputText>
                                    </p:column>
                                </p:dataTable>
                            </p:rowExpansion>
                        </p:rowExpansion>
                    </p:dataTable>
                </p:panel>
                <p:dialog id="dlg" widgetVar="dlgConfirmarEnvio" header="Confirmar Envio de Marcadoria" width="50%" modal="true" draggable="false" resizable="false" position="top center" >
                    <script>
                        function tes1(clas){
                            $("button."+clas+" > .ui-button-text").html('Aguarde');
                            $("button."+clas+" > .ui-icon").removeClass('confirmar').addClass( 'Carregando' );
                            document.getElementById('frm:btn').disabled = true;
                        }
                        function tes2(clas){
                            $("button."+clas+" > .ui-button-text").html('Confirmar Envio de Mercadoria');
                            $("button."+clas+" > .ui-icon").removeClass( 'Carregando' ).addClass( 'confirmar' );
                            document.getElementById('frm:btn').disabled = false;
                        }
                    </script>
                    <h:form id="frmRatreio">
                        <div class="row">
                            <div class="col-lg-12">
                                <h4>Confirmação do envio/retirada destas mercadorias?</h4>
                                <h:outputText value="Você " />
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Produto</th>
                                            <th>Quantidade</th>
                                            <th>Valor</th>
                                            <th>Total</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <ui:repeat value="#{vendasMB.comprasSelecionadas}" var="cmp" >
                                            <tr>
                                                <td><h:outputText value="#{cmp.idProduto.nome}" /></td>
                                                <td><h:outputText value="#{cmp.quantidade}" /></td>
                                                <td><ux:outputMoney value="#{cmp.valorCompra}" /></td>
                                                <td><ux:outputMoney value="#{cmp.valorTotal}" /></td>
                                            </tr>
                                        </ui:repeat>
                                    </tbody>
                                </table>
                                <h4>Endereço de Entrega</h4>
                                <div class="col-lg-12">
                                    <div class="well" style="width: 100% !important;">
                                        <h:outputText value="#{vendasMB.enderecoEntrega()}" />
                                    </div>
                                </div>
                                <p:outputLabel for="cod" value="Código de Rastreamento/Mensagem"/>
                                <p:inputText id="cod" value="#{vendasMB.compra.codigoRastreamentoEntrega}"  required="true"/>
                                <hr/>
                                <p:commandButton id="btnEnvio" value="Confirmar Envio de Mercadoria"  icon="confirmar" styleClass="btn btn-primary bot" update=":vendas, @form, :mess" action="#{vendasMB.atualizarEntrega()}" onclick="tes1('bot')"
                                                 oncomplete="tes2('bot'); if(!args.validationFailed )PF('dlgConfirmarEnvio').hide();"/>
                            </div>
                        </div>
                    </h:form>
                </p:dialog>
            </ui:define>

        </ui:composition>

    </body>
</html>